/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ChallengeDefinition {
  /**
   * Titre de l'exercice
   */
  title: string;
  /**
   * Description de l'exercice (en markdown)
   */
  description: string;
  /**
   * Code de base fourni pour l'exercice
   */
  code?: string;
  tests: {
    /**
     * Titre du test
     */
    title: string;
    /**
     * Variable donnée à l'algorithme en entrée
     */
    in: {
      /**
       * This interface was referenced by `undefined`'s JSON-Schema definition
       * via the `patternProperty` "^[A-Z]+$".
       */
      [k: string]: string | number | unknown[];
    };
    /**
     * Sortie attendue
     */
    out: string[];
  }[];
}
